### ISSUE TITLE
Error during build IMGT library

### ISSUE THREAD

**Issue by xww52526** [repseqio/repseqio#52]
Hi, thanks for this nice software.

I recently downloaded monkey fasta from IMGT, and tried to generate json file. But got following error message. Could you please help me identify what's the cause of error?

`repseqio fromFasta --taxon-id 9544 --species-name rhesus_monkey --species-name macaca_mulatta   --chain  TRG  --name-index 1   --gene-type  V  --gene-feature  VRegion TRGV.fasta my_library.json`
`Exception in thread "main" java.lang.IllegalArgumentException: Unknown symbol "."
	at com.milaboratory.core.sequence.AbstractArraySequence.dataFromChars(AbstractArraySequence.java:85)
	at com.milaboratory.core.sequence.AbstractArraySequence.<init>(AbstractArraySequence.java:29)
	at com.milaboratory.core.sequence.NucleotideSequence.<init>(NucleotideSequence.java:134)
	at io.repseq.cli.FromFastaActionAbstract.go(FromFastaActionAbstract.java:87)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:155)
	at io.repseq.cli.Main.main(Main.java:100)`

Thanks for your help!

**Comment by rhythms06** [comment]
Having this problem too, working with chicken FASTAs from IMGT. Strange, IGHD, IGHJ, and IGLJ compile fine, whereas IGHV and IGLV do not. It must be a problem with V gene libraries. Were you able to find any workarounds @xww52526?

**Comment by suntaosimon** [comment]
I manually deleted the dots(symbol ".") in the sequence and `repseqio fromFasta` works.
