### ISSUE TITLE
Error after using the compiled cat's TCR library

### ISSUE THREAD

**Issue by Kaj-cyber** [repseqio/repseqio#59]
Dear @mikessh ,

I compiled json library for cat's TCR using 'repseqio' as attached file. The command lines were as followed:
### TRA - V and J
`repseqio fromPaddedFasta --species-name Felist_catus --species-name cat -t 183798 -i -f -c TRA -j 3 -n 1 -g V -PFR1Begin=0 -PCDR1Begin=78 -PFR2Begin=114 -PCDR2Begin=165 -PFR3Begin=195 -PCDR3Begin=309 -PVEnd=-1 TRAV.fasta TRAV.json.fasta TRAV.json `
`repseqio fromPaddedFasta --species-name cat -t 183798 -i -f -c TRA -j 3 -n 1 -g J -PJBegin=0 -PFR4Begin=-31 -LFR4Begin='[WF](G.G)' -PFR4End=-1 TRAJ.fasta TRAJ.json.fasta TRAJ.json`

### TRB - VDJ
`repseqio fromPaddedFasta --species-name Felist_catus --species-name cat -t 183798 -i -f -c TRB -j 3 -n 1 -g V -PFR1Begin=0 -PCDR1Begin=78 -PFR2Begin=114 -PCDR2Begin=165 -PFR3Begin=195 -PCDR3Begin=309 -PVEnd=-1 TRBV.fasta TRBV.json.fasta TRBV.json`
`repseqio fromPaddedFasta --species-name cat -t 183798 -i -f -c TRB -j 3 -n 1 -g D TRBD.fasta TRBD.json.fasta TRBD.json`
`repseqio fromPaddedFasta --species-name cat -t 183798 -i -f -c TRB -j 3 -n 1 -g J -PJBegin=0 -PFR4Begin=-31 -LFR4Begin='[WF](G.G)' -PFR4End=-1 TRBJ.fasta TRBJ.json.fasta TRBJ.json`

### TRD - VDJ
repseqio fromPaddedFasta --species-name Felist_catus --species-name cat -t 183798 -i -f -c TRD -j 3 -n 1 -g V -PFR1Begin=0 -PCDR1Begin=78 -PFR2Begin=114 -PCDR2Begin=165 -PFR3Begin=195 -PCDR3Begin=309 -PVEnd=-1 TRDV.fasta TRDV.json.fasta TRDV.json
repseqio fromPaddedFasta --species-name Felist_catus --species-name cat -t 183798 -i -f -c TRD -j 3 -n 1 -g D TRDD.fasta TRDD.json.fasta TRDD.json
repseqio fromPaddedFasta --species-name Felist_catus --species-name cat -t 183798 -i -f -c TRD -j 3 -n 1 -g J -PJBegin=0 -PFR4Begin=-31 -LFR4Begin='[WF](G.G)' -PFR4End=-1 TRDJ.fasta TRDJ.json.fasta TRDJ.json

### TRG - VJ
`repseqio fromPaddedFasta --species-name Felist_catus --species-name cat -t 183798 -i -f -c TRG -j 3 -n 1 -g V -PFR1Begin=0 -PCDR1Begin=78 -PFR2Begin=114 -PCDR2Begin=165 -PFR3Begin=195 -PCDR3Begin=309 -PVEnd=-1 TRGV.fasta TRGV.json.fasta TRGV.json`
`repseqio fromPaddedFasta --species-name Felist_catus --species-name cat -t 183798 -i -f -c TRG -j 3 -n 1 -g J -PJBegin=0 -PFR4Begin=-31 -LFR4Begin='[WF](G.G)' -PFR4End=-1 TRGJ.fasta TRGJ.json.fasta TRGJ.json`

### Merging several libraries into single file and inferring
`repseqio merge *.json imgt.json`
`repseqio inferPoints -g VRegion -g JRegion -f imgt.json imgt.json`

After I tried the complied imgt.json with the cat's TCR fastq files using MiXCR with the command as follows:
```
$MIXCR analyze amplicon \
--threads 20 \
--library imgt \
--species "cat" \
--starting-material rna \
--5-end v-primers \
--3-end j-primers \
--adapters adapters-present \
--receptor-type tcr \
--region-of-interest VDJRegion \
--only-productive \
--align "-OreadsLayout=Collinear" \
--assemble "-OseparateByC=true" \
--assemble "-OqualityAggregationType=Average" \
--assemble "-OclusteringFilter.specificMutationProbability=1E-5" \
--assemble "-OmaxBadPointsPercent=0" \
SRR10350408_1.fq SRR10350408_2.fq test.analysis

```
I've got the these errors:
```
picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAnalyze$CommandAmplicon@344344fa): java.lang.ArrayIndexOutOfBoundsException: Index 19 out of bounds for length 19
        at picocli.CommandLine.execute(CommandLine.java:1004)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:76)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:65)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
        at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:89)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:59)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 19 out of bounds for length 19
        at io.repseq.core.AbstractReferencePoints.getWrappingGeneFeature(AbstractReferencePoints.java:198)
        at io.repseq.core.VDJCLibrary.getChecksum(VDJCLibrary.java:89)
        at io.repseq.core.VDJCLibrary.getLibraryId(VDJCLibrary.java:206)
        at com.milaboratory.mixcr.cli.CommandAlign.getConfiguration(CommandAlign.java:308)
        at com.milaboratory.mixcr.cli.CommandAlign.getFullPipelineConfiguration(CommandAlign.java:299)
        at com.milaboratory.cli.ACommandWithSmartOverwrite.handleExistenceOfOutputFile(ACommandWithSmartOverwrite.java:76)
        at com.milaboratory.cli.ACommandWithOutput.validate(ACommandWithOutput.java:45)
        at com.milaboratory.cli.ACommandWithSmartOverwrite.validate(ACommandWithSmartOverwrite.java:61)
        at com.milaboratory.mixcr.cli.CommandAlign.validate(CommandAlign.java:382)
        at com.milaboratory.mixcr.cli.CommandAnalyze.inheritOptionsAndValidate(CommandAnalyze.java:320)
        at com.milaboratory.mixcr.cli.CommandAnalyze.getAlign(CommandAnalyze.java:338)
        at com.milaboratory.mixcr.cli.CommandAnalyze.run0(CommandAnalyze.java:668)
        at com.milaboratory.cli.ACommand.run(ACommand.java:90)
        at picocli.CommandLine.execute(CommandLine.java:996)
        ... 7 more

```
I presumed the problem should be due to my compiled imgt.json file. It would be very kind of you if you could guide/help me compiling it correctly.

Best regards,
Kaj
[imgt.zip](https://github.com/repseqio/repseqio/files/7147017/imgt.zip)

**Comment by Kaj-cyber** [comment]
After I carefully read about notice for creating library from IMGT-style padded fasta file, I specified positions of anchor points in D region and the library worked perfectly. Your wiki note really saved me. Thank you very much.
